Vagrant.configure("2") do |config|

  config.vm.define "scriptbox" do |scriptbox|
    scriptbox.vm.box = "ubuntu/bionic64"
	  scriptbox.vm.network "private_network", ip: "192.168.10.2"
    scriptbox.vm.hostname = "scriptbox"
	  scriptbox.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
   end
  end

  config.vm.define "web01" do |web01|
    web01.vm.box = "geerlingguy/centos7"
	web01.vm.network "private_network", ip: "192.168.10.3"
        web01.vm.hostname = "web01"
  end
  
  config.vm.define "web02" do |web02|
    web02.vm.box = "geerlingguy/centos7"
	  web02.vm.network "private_network", ip: "192.168.10.4"
    web02.vm.hostname = "web02"
  end

end
